sudo: required
services:
 -docker
 
before_install:
 -docker build -t aye20-github/multi-docker -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true aye20-github/multi-docker npm test -- --coverage

after_success:
 -docker build -t aye20-github/multi-client ./client
 -docker build -t aye20-github/multi-nginx ./nginx
 -docker build -t aye20-github/multi-server ./server
 -docker build -t aye20-github/multi-worker ./worker

 - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_ID" --password-stdin
 
 -docker push aye20-github/multi-client
 -docker push aye20-github/multi-nginx
 -docker push aye20-github/multi-server
 -docker push aye20-github/multi-worker
