sudo: required
services:
 - docker

before_install:
 - docker build -t aye20dockerhub/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true aye20dockerhub/react-test npm test -- --coverage

after_success:
 - docker build -t aye20dockerhub/multi-client ./client
 - docker build -t aye20dockerhub/multi-nginx ./nginx
 - docker build -t aye20dockerhub/multi-server ./server
 - docker build -t aye20dockerhub/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push aye20dockerhub/multi-client
 - docker push aye20dockerhub/multi-nginx
 - docker push aye20dockerhub/multi-server
 - docker push aye20dockerhub/multi-worker

deploy:
 provider: elasticbeanstalk
 region: us-east-1
 app: multi-docker
 env: MultiDocker-env-bean
 bucket_name: elasticbeanstalk-us-east-1-013273932492
 bucket_path: docker-multi
 on: 
  branch: master
 access_key_id: 
  secure: $AWS_ACCESS_KEY
 secret_access_key:
  secure: $AWS_SECRET_KEY
